// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOpekx40LqTs09uBG_vu9Mfa49r8KwnFg',
    appId: '1:1069145751377:web:3024470d7c5eb31b399d70',
    messagingSenderId: '1069145751377',
    projectId: 'library-management-9a198',
    authDomain: 'library-management-9a198.firebaseapp.com',
    storageBucket: 'library-management-9a198.firebasestorage.app',
    measurementId: 'G-F4TZJFBWRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGxLhr3TPa1qjpgjtN0rzuvXhgMjtZ4g',
    appId: '1:1069145751377:android:bda6edb670e8d322399d70',
    messagingSenderId: '1069145751377',
    projectId: 'library-management-9a198',
    storageBucket: 'library-management-9a198.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8L4RFw0ECRwyq8or0o7u9KKHxMhQVtXI',
    appId: '1:1069145751377:ios:453bd30d9be12149399d70',
    messagingSenderId: '1069145751377',
    projectId: 'library-management-9a198',
    storageBucket: 'library-management-9a198.firebasestorage.app',
    iosClientId: '1069145751377-82521ohjql7n1i7cpfuo75etm0ivf813.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagemnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8L4RFw0ECRwyq8or0o7u9KKHxMhQVtXI',
    appId: '1:1069145751377:ios:453bd30d9be12149399d70',
    messagingSenderId: '1069145751377',
    projectId: 'library-management-9a198',
    storageBucket: 'library-management-9a198.firebasestorage.app',
    iosClientId: '1069145751377-82521ohjql7n1i7cpfuo75etm0ivf813.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagemnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOpekx40LqTs09uBG_vu9Mfa49r8KwnFg',
    appId: '1:1069145751377:web:1275d0393b6afe78399d70',
    messagingSenderId: '1069145751377',
    projectId: 'library-management-9a198',
    authDomain: 'library-management-9a198.firebaseapp.com',
    storageBucket: 'library-management-9a198.firebasestorage.app',
    measurementId: 'G-74Q3EXHLEK',
  );

}